In [19]:
import numpy as np

def public_information():
    rounds = np.random.randint(2,10)
    periods = np.random.randint(2,10)
    return rounds, periods

def private_information(num_bidders, num_askers, rounds):
    token_bidders = np.random.randint(0,10) + np.random.randint(0,10) + np.random.randint(0,10, (num_bidders,1))+ np.random.randint(0,10, (num_bidders,rounds))
    token_askers = np.random.randint(0,10) + np.random.randint(0,10,(num_askers,1))+ np.random.randint(0,10,(num_bidders,rounds))
    return token_bidders, token_askers
 
rounds, periods = public_information()
token_bidders, token_askers = private_information(3,3,rounds)

In [21]:
token_bidders, token_askers

(array([[21, 20, 22, 19, 19, 18, 22, 19, 21],
        [15, 22, 21, 20, 18, 16, 16, 15, 23],
        [20, 21, 19, 19, 13, 12, 16, 12, 17]]),
 array([[18, 16, 21, 15, 14, 15, 21, 19, 14],
        [19, 12, 13, 15, 19, 15, 20, 15, 12],
        [14, 15, 20, 23, 22, 21, 21, 16, 21]]))

In [ ]:
def random_bidder(token_value):
    return 

In [11]:
import numpy as np

offer_space = np.linspace(0,1,11)
token_space = np.linspace(0,1,11)
bids = np.random.choice(offer_space, 3)
asks = np.random.choice(offer_space, 3)
  
def token_values

def bid_ask_step(bids, asks):
    current_bid, current_bidder_idx = np.max(bids), np.argmax(bids)
    current_ask, current_asker_idx = np.min(asks), np.argmin(asks)
    return current_bid, current_bidder_idx, current_ask, current_asker_idx
    
    
def buy_sell_step(current_bidder_idx,current_asker_idx, current_bid, current_ask):
    bidder_sell_function = bidder_sell_functions[current_bidder_idx]
    asker_buy_function = asker_buy_functions[current_bidder_idx]
    
    if bidder_sell_function(current_bid, current_ask):
        if asker_buy_function(current_bid, current_ask):
            return True
    return False
    
    

    

SyntaxError: invalid syntax (2144529548.py, line 18)

In [9]:
bids, asks

(array([0.7, 0.4, 0.6]), array([1. , 0.3, 0.4]))

In [ ]:
bids = np.array()